language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    # - php: hhvm

sudo: false

cache:
  - apt

addons:
  apt:
    packages:
      - nginx

env:
  - BEHAT_VERSION="2.4.*"
  - BEHAT_VERSION="2.5.*"

before_install:
  # start a web server on port 8081, running in the background
  - bin/start_server.sh

install:
  - composer require behat/behat:${BEHAT_VERSION}
  - composer install --no-interaction --prefer-source
  - composer show -i

script:
  - vendor/bin/behat
