language: php
php:
  - 5.6
  - 5.5
  - 5.4
env:
  - BEHAT_VERSION="2.4.*"
  - BEHAT_VERSION="2.5.*"
install:
  - composer require behat/behat:${BEHAT_VERSION}
  - composer install -v --no-interaction --prefer-source
before_script:
  - php -S localhost:8081 www/router.php &
  - sleep 4
script:
  - vendor/bin/behat
